routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//use Symfony\Component\Routing\Annotation\Route;
use Illuminate\Support\Facades\Route; 
 
Auth::routes();
Route::get('/', 'Admin\AdminController@index')->name('home');
Route::get('/home', 'Admin\AdminController@index')->name('home');
Route::get('admin', 'Admin\AdminController@index');
Route::get('admin/reportes','ReporteController@index');
Route::get('admin/reportes/buscar','ReporteController@buscarventas');
Route::get('admin/reportes/detalle','ReporteController@ventasdetalle');
Route::get('admin/reportes/combustibles','ReporteController@combustibles');
Route::get('admin/reportes/combustible_exportar','ReporteController@combustible_exportar');
Route::get('admin/reportes/exportar','ReporteController@exportar');
Route::get('admin/reportes_detalle/exportar','ReporteController@exportar_detalle')->name('exportar-detalle-reporte');
Route::get('pos/productos/exportar','ProductoController@exportar');
Route::get('pos/creditos/exportar','CreditoController@exportar');
Route::get('pos/vales/exportar','ValeController@exportar');

Route::resource('admin/roles', 'Admin\RolesController');
Route::resource('admin/permissions', 'Admin\PermissionsController');
Route::resource('admin/users', 'Admin\UsersController');
Route::resource('admin/pages', 'Admin\PagesController');
Route::resource('pos/users', 'UserPosController');
Route::resource('pos/clientes', 'ClientePosController');
Route::resource('admin/activitylogs', 'Admin\ActivityLogsController')->only([
    'index', 'show', 'destroy'
]);

// CAJES DE PRODUCTOS
Route::resource('/pos/canjesproductos', 'CanjesProductosController');
Route::get('/canjesproductos/detalle/{id}', 'CanjesProductosController@detalle');
Route::get('/canjesproductos/editar/{id}', 'CanjesProductosController@edit');



Route::resource('admin/settings', 'Admin\SettingsController');
Route::get('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
Route::post('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);

Route::resource('admin/business', 'Admin\\BusinessController');
Route::resource('admin/business', 'Admin\\BusinessController');
Route::resource('admin/business', 'Admin\\BusinessController');
 
Route::resource('admin/configurationB', 'Admin\\ConfigurationBController');
Route::resource('admin/configurationB', 'Admin\\ConfigurationBController');
Route::resource('admin/configurationB', 'Admin\\ConfigurationBController'); 
// Route::resource('pos/vales', 'ValeController');
Route::resource('pos/creditos', 'CreditoController');
Route::resource('pos/productos', 'ProductoController');
Route::resource('pos/caja', 'CajaController');
Route::resource('pos/clientes_sunat', 'ClienteSunatController');
Route::resource('pos/descuentos', 'DescuentoController');
Route::get('pos/descuentos/ver/{id_cliente}', 'DescuentoController@ver');
Route::resource('facturacion/comprobantes', 'ComprobantesController');
//Route::resource('pos/valesdetalle/{id_vale}', 'ValeController@detalle');
Route::get('pos/credito/{id_cliente}','CreditoController@credito_cliente');
Route::get('pos/cajaresumen','CajaController@generar')->name('resumen');
Route::get('dashboard','Admin\AdminController@index');
Route::get('pos/vales/listar/{id_credito}', 'ValeController@index');
Route::get('pos/vales/crear/{id_credito}', 'ValeController@create');
Route::get('pos/vales/editarpago/{id_credito}', 'ValeController@editarpago');

Route::post('pos/vales/save', 'ValeController@save'); 
 
Route::get('pos/vales/{id}', 'ValeController@show');

Route::get('pos/vales/infoPagos/{id}', 'ValeController@infoPagos');


Route::get('pos/vales/editar/{id}', 'ValeController@edit');
Route::get('pos/creditos/editar/{id}', 'CreditoController@edit'); 
Route::resource('pos/canjes', 'CanjesController');
Route::get('/canjes/despacho','CanjesController@despacho');
Route::get('/canjes/cliente/{num_doc}','CanjesController@cliente');
Route::get('/productos','ProductoController@listar');
Route::get('/canjes/detalle/{id}','CanjesController@detalle');

#Stock
Route::get('/admin/varillaje','StockController@varillaje');
Route::get('/admin/tanks','StockController@tanks');
Route::get('/admin/tanks/{id}','StockController@tanksEdit')->name('edit-tank');
Route::post('/tanks/store','StockController@tanks_store')->name('add-tank');
Route::post('/varillaje/store','StockController@varillaje_store')->name('add-varillaje');
Route::put('/tanks/update/{id}','StockController@tanks_update')->name('update-tank');


#Reportes
Route::get('/admin/reportes/tanks','StockController@tanks_report');


#ventas historico
Route::get('/ventas/detalle/{id}','CanjesController@detalleItems');
Route::get('/canjes/exportar','CanjesController@exportar');
Route::get('/canjes_detalle/exportar/{id}','CanjesController@detalles_exportar')->name('exportar-canjes-detalle');
 

app/Http/Controllers/CreditoController.php
<?php

namespace App\Http\Controllers;

use App\Credit;
use App\CreditoProducto;
use App\Cliente;
use App\Producto;
use Illuminate\Http\Request;
use DB;
use Illuminate\Support\Facades\Validator;
use App\Exports\CreditosExport;
use Maatwebsite\Excel\Facades\Excel;

class CreditoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {
            PosController::ChangeDB();
            return $next($request);
        });
    }

    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 10;
        if (!empty($keyword)) {
            $creditos = DB::connection('tenant')->table('creditos')
                ->join('clientes', 'creditos.id_cliente', '=', 'clientes.id')
                ->select('creditos.*', 'clientes.nro_doc', 'clientes.nombres')
                ->where('creditos.estado',"=","A")
                ->where('clientes.nombres', 'LIKE', "%$keyword%")->orWhere('clientes.nro_doc', 'LIKE', "%$keyword%")
                ->orderBy('id', 'desc')
                ->paginate($perPage);
        } else {
            $creditos = DB::connection('tenant')->table('creditos')
                ->join('clientes', 'creditos.id_cliente', '=', 'clientes.id')
                ->select('creditos.*', 'clientes.nro_doc', 'clientes.nombres')
                ->where('creditos.estado',"=","A")
                ->orderBy('id', 'desc')
                ->paginate($perPage);
        }

        return view('pos/creditos.index', compact('creditos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clientes = Cliente::all();
        $productos = Producto::where('tipo', 'P')->get();
        return view('pos/creditos.create', compact('clientes', 'productos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //var_dump($request->all());exit;
        $post    = $request->all();
        $validator = Validator::make($request->all(), [
            "monto" => "required",
            "id_cliente" => "required",
            "cantidad" => "required"
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput($post);
        }
        $productos = $post["cantidad"];
        $descuento = $post["descuento"];
        $codigo = $post["codigo"];
        $credito = new Credit();
        $credito->id_cliente = $post['id_cliente'];
        $credito->monto = $post['monto'];
        $credito->saldo = $post['monto'];
        $credito->estado = "A";
        $credito->save();
        for($i=0;$i<count($productos);$i++){
            $credito_producto = new CreditoProducto();
            $credito_producto->id_credito = $credito->id;
            $credito_producto->id_producto = $codigo[$i];
            $credito_producto->cantidad = $productos[$i];
            $credito_producto->descuento = $descuento[$i];
            $credito_producto->estado = "A";
            $credito_producto->save();
        }       
        return redirect('pos/creditos')->with('success', 'El Crédito fue creado correctamente');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $credito=Credit::find($id);
        $credito_productos = DB::connection('tenant')->table('creditos_producto')
                ->join('productos', 'productos.id', '=', 'creditos_producto.id_producto')
                ->select('creditos_producto.*', 'productos.descripcion', 'productos.codigo')                
                ->where('creditos_producto.id_credito',$id)
                ->orderBy('id', 'desc')
                ->get();
        $clientes=Cliente::where('id',$credito->id_cliente)->get();
        $productos=Producto::where('tipo','P')->get();
        return view('pos.creditos/edit',compact('credito','clientes','productos','credito_productos'));
    }
    public function exportar(Request $request)
    {
        $perPage = 10;

        $creditos = DB::connection('tenant')->table('creditos')
            ->join('clientes', 'creditos.id_cliente', '=', 'clientes.id')
            ->select('creditos.id_cliente', 'creditos.id', 'clientes.nro_doc', 'clientes.nombres')
            ->orderBy('id', 'desc')->get();
        return Excel::download(new CreditosExport($creditos), 'creditos.xlsx');
    }

    public function update(Request $request, $id)
    {
        $post    = $request->all();
        $validator = Validator::make($request->all(), [
            "monto" => "required",
            "id_cliente" => "required",
            "cantidad" => "required"
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput($post);
        }
        $productos = $post["cantidad"];
        $descuento = $post["descuento"];
        $codigo = $post["codigo"];
        $credito_producto_id=$post["credito_producto_id"];
        
        $credito = Credit::find($id);
        $credito->id_cliente = $post['id_cliente'];
        $credito->monto = $post['monto'];
        $credito->saldo = $post['saldo'];
        $credito->save();
        for($i=0;$i<count($productos);$i++){
            $credito_producto = CreditoProducto::find($credito_producto_id[$i]);
            $credito_producto->id_credito = $credito->id;
            $credito_producto->id_producto = $codigo[$i];
            $credito_producto->cantidad = $productos[$i];
            $credito_producto->descuento = $descuento[$i];
            $credito_producto->estado = "A";
            $credito_producto->save();
        }       
        return redirect('pos/creditos')->with('success', 'El Crédito fue actualizado correctamente');
    }

    public function destroy($id)
    {
        $credito=Credit::find($id);
        $credito->estado="N";
        $credito->save();
        return redirect('pos/creditos')->with('success', 'El Crédito fue actualizado correctamente');
    }

    public function credito_cliente($id_cliente)
    {
        $creditos = Credit::where("id_cliente", "=", $id_cliente)->get();

        return $creditos;

    }
}
 

app/Http/Controllers/PosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Business;
use DB;

class PosController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');        
    }

    public static function ChangeDB()
    {        
        $user = auth()->user();        
        $business_id = $user->business_id;
        $business = Business::find($business_id);                        
        $connectionString = explode('|', $business->connection_string);
        /*$connectionString[0]=port;$connectionString[1]=user;$connectionString[2]=password;
        $connectionString[3]=database;*/
        config(['database.connections.tenant.driver' => $business->database_driver]);
        config(['database.connections.tenant.host' => $business->ip]);
        config(['database.connections.tenant.port' => $connectionString[0]]);
        config(['database.connections.tenant.username' => $connectionString[1]]);
        config(['database.connections.tenant.password' => $connectionString[2]]);
        config(['database.connections.tenant.database' => $connectionString[3]]);
        DB::purge('tenant');
        DB::reconnect('tenant');        
    }
}

resources/views/pos/creditos/create.blade.php
@extends('layouts.dashboard')
@section('content')
<div id="page-wrapper">
    <div class="header">
        <h1 class="page-header">
            CRÉDITOS
        </h1>
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Dashboard</a></li>
            <li class="active">Créditos</li>
        </ol>

    </div>
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <a href="/pos/creditos" class="btn btn-sm btn-success">Listado de Créditos</a>
            </div>
        </div>

        <br>
        <div id="agregar-usuario_pos">
            <form method="POST" action="/pos/creditos">
                @csrf
                <div class="form-group row">
                    <div class="col-md-12">
                        <label for="password" class="col-form-label text-md-right">{{ __('Cliente') }}</label>
                        <select name="id_cliente" class=" select">
                            @foreach ($clientes as $item)
                            <option value="{{$item->id}}">{{$item->nombres}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <label for="monto" class="col-form-label text-md-right">{{ __('Monto') }}</label>
                        <input id="monto" type="text" class="form-control @error('monto') is-invalid @enderror" name="monto" value="{{ old('monto') }}" required autocomplete="monto" autofocus>
                    </div>
                    <div class="col-md-6">
                        <label for="fecha" class="col-form-label text-md-right">{{ __('Fecha de Inicio') }}</label>
                        <input id="fecha" type="date" class="form-control @error('fecha') is-invalid @enderror" name="fecha" value="{{ old('fecha') }}" required>

                        @error('password')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <label for="">Productos</label>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>CÓDIGO</th>
                            <th>DESCRIPCIÓN</th>
                            <th>CANTIDAD</th>
                            <th>DESCUENTO</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php $cont=0 @endphp
                        @foreach ($productos as $item)
                        <tr>
                            <td>{{$item->id}}</td>
                            <td>{{$item->codigo}}</td>
                            <td>{{$item->descripcion}}</td>
                            <td>
                                <input type="hidden" name="codigo[{{$cont}}]" value="{{$item->id}}">
                                <input type="number" min="0" class="" required name="cantidad[{{$cont}}]" value="{{ old('cantidad.'.$item->id) }}"></td>
                            <td><input type="number" min="0" step="any" class="" required name="descuento[{{$cont}}]" value="{{ old('cantidad.'.$item->id) }}"></td>
                        </tr>
                        @php $cont++ @endphp
                        @endforeach
                    </tbody>
                </table>
                <br>
                <div class="form-group row mb-0">
                    <div class="col-md-12">
                        <button type="submit" class="col-md-12 btn btn-primary">
                            {{ __('Registrar') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pos/creditos/edit.blade.php
@extends('layouts.dashboard')
@section('content')
<div id="page-wrapper">
    <div class="header">
        <h1 class="page-header">
            CRÉDITOS
        </h1>
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Dashboard</a></li>
            <li class="active">Créditos</li>
        </ol>

    </div>
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <a href="/pos/creditos" class="btn btn-sm btn-success">Listado de Créditos</a>
            </div>
        </div>

        <br>
        <div id="agregar-usuario_pos">
            <form method="POST" action="/pos/creditos/{{$credito->id}}">
            {{ method_field('PUT') }}
                @csrf
                <div class="form-group row">
                    <div class="col-md-12">
                        <label for="password" class="col-form-label text-md-right">{{ __('Cliente') }}</label>
                        <select name="id_cliente" class="class=" form-control js-select2">
                            @foreach ($clientes as $item)
                            <option value="{{$item->id}}">{{$item->nombres}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <label for="monto" class="col-form-label text-md-right">{{ __('Monto') }}</label>
                        <input id="monto" value={{$credito->monto}} type="text" class="form-control @error('monto') is-invalid @enderror" name="monto" value="{{ old('monto') }}" required autocomplete="monto" autofocus>
                    </div>
                    <div class="col-md-6">
                        <label for="fecha" class="col-form-label text-md-right">{{ __('Fecha de Inicio') }}</label>
                        <input id="fecha" value="{{date('Y-m-d', strtotime($credito->created_at))}}" type="date" class="form-control @error('fecha') is-invalid @enderror" name="fecha" value="{{ old('fecha') }}" required>

                        @error('password')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <label for="monto" class="col-form-label text-md-right">{{ __('Consumido') }}</label>
                        <input  type="text" value="{{$credito->monto-$credito->saldo}}" class="form-control @error('consumido') is-invalid @enderror" name="consumido" value="{{ old('consumido') }}" required autocomplete="monto" autofocus>
                    </div>
                    <div class="col-md-6">
                        <label for="fecha" class="col-form-label text-md-right">{{ __('Saldo') }}</label>
                        <input  type="text"  value={{$credito->saldo}} class="form-control @error('saldo') is-invalid @enderror" name="saldo" value="{{ old('saldo') }}" required>

                        @error('password')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>
                </div>
                <label for="">Productos</label>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>CÓDIGO</th>
                            <th>DESCRIPCIÓN</th>
                            <th>CANTIDAD</th>
                            <th>DESCUENTO</th>
                        </tr>
                    </thead>
                    <tbody>
                    @php $cont=0 @endphp
                        @foreach ($credito_productos as $item)                            
                        <tr>
                            <td>{{$item->id}}</td>
                            <td>{{$item->codigo}}</td>
                            <td>{{$item->descripcion}}</td>
                            <td>                                
                            <input type="hidden" name="credito_producto_id[{{$cont}}]" value="{{$item->id}}"   > 
                            <input type="hidden" name="codigo[{{$cont}}]" value="{{$item->id_producto}}"   > 
                            <input type="number" value="{{$item->cantidad}}" step="any" min="0" class="" required name="cantidad[{{$cont}}]" value="{{ old('cantidad.'.$item->id) }}"></td>
                            <td><input type="number" value="{{$item->descuento}}" min="0" step="any" class="" required name="descuento[{{$cont}}]" value="{{ old('cantidad.'.$item->id) }}"></td>
                        </tr>
                        @php $cont++ @endphp
                        @endforeach
                    </tbody>
                </table>
                <br>
                <div class="form-group row mb-0">
                    <div class="col-md-12">
                        <button type="submit" class="col-md-12 btn btn-primary">
                            {{ __('Registrar') }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/pos/creditos/index.blade.php
@extends('layouts.dashboard')
@section('content')
<div id="page-wrapper">
    <div class="header">
        <h1 class="page-header">
            CRÉDITOS
        </h1>
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Dashboard</a></li>
            <li class="active">Créditos</li>
        </ol>

    </div>
    <div id="page-inner">
        <div class="row">
            <div class="col-md-6">
                <a href="/pos/creditos" class="btn btn-sm btn-success">Listado de Créditos</a>
                <a href="/pos/creditos/create" class="btn btn-sm btn-primary text-white">Agregar <i class="fa fa-plus"></i></a>
                <a href="/pos/creditos/exportar" class="btn btn-success btn-sm">
                    Exportar <i class="fa fa-file-excel-o"></i>
                </a>
            </div>
            <div class="col-md-6">
                <form method="GET" action="/pos/creditos" accept-charset="UTF-8" class="form-inline my-2 my-lg-0 float-right" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search" value="{{ old('search') }}" placeholder="Search...">
                        <span class="input-group-addon">
                            <button class="btn btn-sm btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>

                    </div>
                    <br>
                </form>
            </div>
        </div>
        <div class="">
            <br>
            <div class="table-responsive">
                <br>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>ID_CLIENTE</th>
                            <th>ID_CREDITO</th>
                            <th>FECHA</th>
                            <th>RUC</th>
                            <th>Cliente</th>
                            <th>Monto</th>
                            <th>Usado</th> 
                            <th>Saldo</th>
                            <th>Movimientos</th>
                            <th>Editar</th>
                            <th>Deshabilitar</th>
                        </tr>
                        <thead>
                        <tbody>
                            @foreach($creditos as $credito)
                            <tr>
                                <td>{{$credito->id_cliente}}</td>
                                <td>{{$credito->id}}</td>
                                <td>{{$credito->created_at}}</td>
                                <td>{{$credito->nro_doc}}</td>
                                <td>{{$credito->nombres}}</td>
                                <td>{{$credito->monto}}</td>
                                <td>{{$credito->monto-$credito->saldo}}</td>
                                <td>{{$credito->saldo}}</td>
                                <td class="text-center"><a class="btn btn-sm" target="_blank" href="vales/listar/{{$credito->id}}"><i class="fa fa-eye" aria-hidden="true"></i></a></td>
                                <td class="text-center">
                                    <a href="creditos/editar/{{$credito->id}}/" class="btn text-center btn-sm btn-info text-white "><i class="fa fa-edit "></i></a>
                                </td>
                                <td>
                                    <form action="{{ route('creditos.destroy', $credito->id) }}" method="POST">
                                        {{ csrf_field() }} {{ method_field('delete') }}
                                        <button type="submit" class="btn text-center btn-sm btn-danger text-white">
                                        <i class="fa fa-ban"></i>
                                        </button>
                                    </form>
                                </td>                                
                            </tr>
                            @endforeach
                        </tbody>
                </table>
                {{ $creditos->links() }}
            </div>
        </div>
    </div>
</div>
@endsection